import { Link } from "react-router-dom";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const NAKSHATRA_REFERENCE = [
  ["Ashwini", "Aries 0°00′–13°20′", "Ketu", "Ashwini Kumaras", "Chu, Che, Cho, La", "Beginning, speed and healing; energetic initiative with a need to manage impatience."],
  ["Bharani", "Aries 13°20′–26°40′", "Venus", "Yama", "Li, Lu, Le, Lo", "Responsibility, endurance, desire and transformation through learning boundaries."],
  ["Krittika", "Aries 26°40′–Taurus 10°00′", "Sun", "Agni", "A, Ee, U, E", "Purification, determination and sharp discernment that can become overly critical."],
  ["Rohini", "Taurus 10°00′–23°20′", "Moon", "Prajapati", "O, Va, Vi, Vu", "Growth, beauty, creativity, attraction and the search for emotional security."],
  ["Mrigashirsha", "Taurus 23°20′–Gemini 6°40′", "Mars", "Soma", "Ve, Vo, Ka, Ki", "Curiosity, exploration and searching, with restlessness as the main challenge."],
  ["Ardra", "Gemini 6°40′–20°00′", "Rahu", "Rudra", "Ku, Gha, Na, Chha", "Intensity, deep questioning and renewal after experiences that clear stagnation."],
  ["Punarvasu", "Gemini 20°00′–Cancer 3°20′", "Jupiter", "Aditi", "Ke, Ko, Ha, Hi", "Return, resilience, optimism and the ability to rebuild after setbacks."],
  ["Pushya", "Cancer 3°20′–16°40′", "Saturn", "Brihaspati", "Hu, He, Ho, Da", "Nourishment, learning, duty and disciplined support for other people."],
  ["Ashlesha", "Cancer 16°40′–30°00′", "Mercury", "Nagas", "Di, Du, De, Do", "Psychological perception, strategy and hidden layers, with overthinking as a risk."],
  ["Magha", "Leo 0°00′–13°20′", "Ketu", "Pitris", "Ma, Mi, Mu, Me", "Ancestors, heritage, legacy, status and responsibility in leadership."],
  ["Purva Phalguni", "Leo 13°20′–26°40′", "Venus", "Bhaga", "Mo, Ta, Ti, Tu", "Pleasure, creativity, romance and the capacity to enjoy what life has created."],
  ["Uttara Phalguni", "Leo 26°40′–Virgo 10°00′", "Sun", "Aryaman", "Te, To, Pa, Pi", "Commitment, agreements, partnership and relationships designed to endure."],
  ["Hasta", "Virgo 10°00′–23°20′", "Moon", "Savitar", "Pu, Sha, Na, Tha", "Craftsmanship, dexterity and turning an idea into something tangible."],
  ["Chitra", "Virgo 23°20′–Libra 6°40′", "Mars", "Tvashtar", "Pe, Po, Ra, Ri", "Design, brilliance, structure and technically refined visual creation."],
  ["Swati", "Libra 6°40′–20°00′", "Rahu", "Vayu", "Ru, Re, Ro, Ta", "Independence, adaptability and freedom, balanced against instability."],
  ["Vishakha", "Libra 20°00′–Scorpio 3°20′", "Jupiter", "Indra and Agni", "Ti, Tu, Te, To", "Purpose, ambition and concentration toward a chosen objective."],
  ["Anuradha", "Scorpio 3°20′–16°40′", "Saturn", "Mitra", "Na, Ni, Nu, Ne", "Friendship, loyalty, cooperation and disciplined devotion."],
  ["Jyeshtha", "Scorpio 16°40′–30°00′", "Mercury", "Indra", "No, Ya, Yi, Yu", "Experience, seniority, protection and earned authority without excessive control."],
  ["Mula", "Sagittarius 0°00′–13°20′", "Ketu", "Nirriti", "Ye, Yo, Bha, Bhi", "Roots, investigation and radical transformation through discovering causes."],
  ["Purva Ashadha", "Sagittarius 13°20′–26°40′", "Venus", "Apah", "Bhu, Dha, Pha, Dha", "Conviction, expression, renewal and defending deeply held beliefs."],
  ["Uttara Ashadha", "Sagittarius 26°40′–Capricorn 10°00′", "Sun", "Vishvadevas", "Bhe, Bho, Ja, Ji", "Lasting achievement built through responsibility and strong foundations."],
  ["Shravana", "Capricorn 10°00′–23°20′", "Moon", "Vishnu", "Ju/Khi, Je/Khu, Jo/Khe, Gha/Kho", "Listening, education, observation and transmitting knowledge."],
  ["Dhanishta", "Capricorn 23°20′–Aquarius 6°40′", "Mars", "Vasus", "Ga, Gi, Gu, Ge", "Rhythm, activity, resources, social participation and achievement."],
  ["Shatabhisha", "Aquarius 6°40′–20°00′", "Rahu", "Varuna", "Go, Sa, Si, Su", "Mystery, healing, solitude and investigation of hidden systems."],
  ["Purva Bhadrapada", "Aquarius 20°00′–Pisces 3°20′", "Jupiter", "Aja Ekapada", "Se, So, Da, Di", "Philosophical intensity, ideals and transformation through conviction."],
  ["Uttara Bhadrapada", "Pisces 3°20′–16°40′", "Saturn", "Ahir Budhnya", "Du, Tha, Jha, Na", "Depth, patience, maturity and stability developed through experience."],
  ["Revati", "Pisces 16°40′–30°00′", "Mercury", "Pushan", "De, Do, Cha, Chi", "Completion, guidance, safe journeys and transition into a new stage."],
];

const contextLinks = [
  ["/dasha-calculator/", "Dasha Calculator", "Use the Moon's birth Nakshatra to calculate Mahadasha, Antardasha and the starting Dasha balance."],
  ["/rashi-calculator-by-date-of-birth", "Rashi Calculator", "Compare the finer Nakshatra division with your broader Chandra Rashi or Moon sign."],
  ["/free-kundli-generator", "Free Kundli Generator", "See the Moon, Ascendant, planets, houses and Nakshatras together in a complete birth chart."],
  ["/ai-kundli-analysis", "AI Kundli Analysis", "Interpret the Nakshatra lord in the context of houses, aspects, conjunctions and the complete horoscope."],
  ["/free-kundali-matching", "Free Kundli Matching", "Use both partners' Moon signs and birth stars within a wider marriage compatibility analysis."],
  ["/ai-marriage-prediction-by-date-of-birth", "Marriage Prediction", "Explore seventh-house, Dasha and relationship indicators beyond Nakshatra compatibility alone."],
  ["/love-astrology-by-date-of-birth", "Love Astrology", "Read emotional and relationship patterns using the full Vedic chart."],
  ["/ai-future-spouse-prediction", "Future Spouse Prediction", "Explore spouse-oriented chart factors alongside the Moon and its Nakshatra."],
  ["/ai-career-prediction-by-date-of-birth", "Career Prediction", "Connect your lunar temperament with career houses, lords, Dashas and planetary strengths."],
  ["/astrology-by-date-of-birth", "Astrology by Date of Birth", "Understand how date, exact time and birthplace combine to create a complete Vedic reading."],
  ["/horoscope-by-date-of-birth", "Horoscope by Date of Birth", "Move from a single birth-star result to a broader personalized horoscope."],
  ["/today-horoscope", "Today's Horoscope", "Keep your fixed birth Nakshatra separate from the Moon's changing daily transit."],
  ["/monthly-prediction", "Monthly Prediction", "View longer current trends while keeping your natal Moon as the chart foundation."],
  ["/lucky-colour-for-today", "Lucky Colour Today", "Explore daily colour guidance informed by Vedic astrology."],
  ["/free-ai-astrologer-chat", "Free AI Astrologer Chat", "Ask follow-up questions about your Nakshatra, pada, lord and complete chart."],
  ["/free-5-minutes-astrology-ai", "Free 5-Minute Astrology", "Get a quick chart-based overview after calculating your birth star."],
  ["/ai-astrology-prediction", "AI Astrology Prediction", "Receive a wider prediction that considers more than one lunar placement."],
  ["/ai-pandit", "AI Pandit", "Ask for simple Vedic explanations and traditional guidance based on your birth details."],
  ["/chatgpt-astrology", "ChatGPT Astrology", "Learn why a true astrology tool calculates planetary longitude instead of guessing from text."],
  ["/blog/vedic-vs-western-astrology", "Vedic vs Western Astrology", "Understand why Lahiri sidereal and Western tropical longitudes differ."],
  ["/blog/how-ai-is-transforming-vedic-astrology", "AI and Vedic Astrology", "See how astronomical calculation and clear AI explanation can work together."],
  ["/blog/is-ai-astrology-accurate", "Is AI Astrology Accurate?", "Separate precise astronomical computation from traditional astrological interpretation."],
  ["/blog/marriage-compatibility-based-on-your-zodiac-sign", "Zodiac Compatibility", "Compare sign-based compatibility with fuller Nakshatra and Kundli matching."],
  ["/blog/manglik-dosha-myths-vs-reality", "Manglik Dosha Guide", "Avoid judging marriage from one placement and understand why complete-chart combinations matter."],
];

export const NAKSHATRA_FAQS = [
  ["What is a Nakshatra Calculator?", "It uses birth date, exact time and birthplace to calculate the Moon's sidereal position and determine the Janma Nakshatra or birth star."],
  ["Can I find Nakshatra by date of birth only?", "Sometimes an estimate is possible, but exact birth time is required when the Moon changes Nakshatra during that date, and pada needs still greater precision."],
  ["How many Nakshatras and Padas are there?", "There are 27 Nakshatras with four Padas each, producing 108 Nakshatra Padas."],
  ["Is Nakshatra calculated from the Sun or Moon?", "Janma Nakshatra is normally calculated from the Moon's position at birth."],
  ["Is Nakshatra the same as Rashi?", "No. Rashi divides the zodiac into 12 signs of 30 degrees; Nakshatra divides it into 27 sections of 13 degrees 20 minutes."],
  ["Does my birth Nakshatra change?", "No. It records the Moon's position at birth. The current transit Nakshatra changes as the Moon continues moving."],
  ["Which Nakshatra is luckiest or best for marriage?", "No single Nakshatra guarantees luck or marriage success. Traditional analysis considers the complete charts and many compatibility factors."],
  ["Can twins have the same Nakshatra?", "Yes. Twins commonly share a Nakshatra and may share a pada, while other chart factors can still differ."],
];

export default function NakshatraSeoContent() {
  return <article className="mx-auto mb-20 max-w-4xl px-4">
    <div className="prose prose-invert max-w-none space-y-10 text-[17px] leading-8 text-white/80 prose-p:text-white/80 prose-strong:text-white">
      <section><h2 className="text-3xl font-bold text-white">Nakshatra Calculator: Find Your Birth Star, Pada, Rashi and Nakshatra Lord</h2><p>Your <strong>Nakshatra</strong>, also called Janma Nakshatra or birth star, is the lunar constellation occupied by the Moon at the exact time of birth in Vedic astrology. This calculator uses birth date, exact birth time and birthplace to identify your Nakshatra, pada, lord, Moon sign, deity, traditional naming syllables and exact Moon position.</p><p>A complete result helps answer “What is my Nakshatra?”, “What is my birth star?” and “Which Nakshatra pada was I born in?” It also provides the starting foundation used by the <Link to="/dasha-calculator/">Vimshottari Dasha Calculator</Link> and compatibility factors used in <Link to="/free-kundali-matching">Kundli matching</Link>.</p></section>
      <section><h2 className="text-3xl font-bold text-white">What Is My Nakshatra?</h2><p>Vedic astrology divides the 360-degree zodiac into 27 Nakshatras. Each covers <strong>13°20′</strong> and contains four Padas of <strong>3°20′</strong>, producing 108 Nakshatra Padas. Two people can share a Nakshatra but have different padas and therefore a more precise lunar subdivision.</p></section>
      <section><h2 className="text-3xl font-bold text-white">What Does a Nakshatra Calculator Do?</h2><p><strong>Birth date + birth time + birth location → Moon longitude → Nakshatra → Pada.</strong> A reliable calculator computes the Moon's astronomical position instead of guessing from a birthday. For example, Ashwini ends at 13°20′ Aries, so a sidereal Moon at 15° Aries falls in Bharani; its exact position inside Bharani determines the pada.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Why Birth Time and Place Matter</h2><p>The Moon moves continuously. Near a Nakshatra boundary, a small time difference can change the birth star; pada is even more sensitive. Birthplace supplies the timezone needed to interpret local birth time correctly, especially for historical timezone changes, daylight saving, births near midnight, or locations outside your current country.</p><p>If birth time is unknown, do not invent 12:00 PM. The Nakshatra may be stable for the date, but a boundary birth can remain uncertain. Exact information is preferable for a <Link to="/free-kundli-generator">complete Kundli</Link>, marriage matching and Dasha calculation.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Nakshatra vs Rashi</h2><p>Your Rashi is the 30-degree Moon sign; Nakshatra is the smaller 13°20′ lunar division containing the same Moon. A person can have Taurus Rashi, Rohini Nakshatra and Pada 2 simultaneously. Use the <Link to="/rashi-calculator-by-date-of-birth">Rashi Calculator</Link> to compare both layers.</p></section>
      <section><h2 className="text-3xl font-bold text-white">The Mathematics Behind 27 Nakshatras</h2><p><strong>360° ÷ 27 = 13⅓° = 13°20′.</strong> Dividing each Nakshatra into four gives <strong>3°20′ per Pada</strong> and exactly 108 Padas. The structure is mathematical; the meanings belong to the traditional interpretive framework of Jyotisha.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Complete 27 Nakshatra Table</h2><p>The nine rulers repeat three times in the fixed order Ketu, Venus, Sun, Moon, Mars, Rahu, Jupiter, Saturn and Mercury—the same order used in Vimshottari Dasha.</p><div className="not-prose mt-5 overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.03]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/5 text-white/70"><tr><th className="px-4 py-3">No.</th><th className="px-4 py-3">Nakshatra</th><th className="px-4 py-3">Zodiac position</th><th className="px-4 py-3">Lord</th><th className="px-4 py-3">Deity</th></tr></thead><tbody>{NAKSHATRA_REFERENCE.map(([name, position, lord, deity], index) => <tr key={name} className="border-t border-white/10"><td className="px-4 py-3 text-white/40">{index + 1}</td><td className="px-4 py-3 font-medium text-white">{name}</td><td className="px-4 py-3">{position}</td><td className="px-4 py-3">{lord}</td><td className="px-4 py-3">{deity}</td></tr>)}</tbody></table></div></section>
      <section><h2 className="text-3xl font-bold text-white">Meaning of All 27 Nakshatras</h2><p>These descriptions are intentionally brief. Moon sign, pada, houses, aspects, planets and the condition of the Nakshatra lord can substantially change the expression. A birth star should never be reduced to one personality adjective.</p><div className="not-prose mt-6 grid gap-4 sm:grid-cols-2">{NAKSHATRA_REFERENCE.map(([name, , lord, deity, , meaning], index) => <div key={name} className="card-glass rounded-2xl border border-white/10 p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-pink-400">{index + 1}. {name}</p><p className="mt-2 text-sm text-white/55"><strong className="text-white">Lord:</strong> {lord} · <strong className="text-white">Deity:</strong> {deity}</p><p className="mt-3 text-sm leading-6 text-white/75">{meaning}</p></div>)}</div></section>
      <section><h2 className="text-3xl font-bold text-white">What Is a Nakshatra Pada?</h2><p>Every Nakshatra contains four quarters: Pada 1 covers 0°00′–3°20′ within the Nakshatra, Pada 2 covers 3°20′–6°40′, Pada 3 covers 6°40′–10°00′, and Pada 4 covers 10°00′–13°20′. This finer location is why traditional naming uses 108 sound groups rather than only 27.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Nakshatra Pada and Baby-Name Starting Sounds</h2><p>Traditional Hindu naming may use the sound assigned to the child's Nakshatra and pada. Transliteration varies across languages and regions, so the spoken sound matters more than one English spelling.</p><div className="not-prose mt-5 overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.03]"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-white/5 text-white/70"><tr><th className="px-4 py-3">Nakshatra</th><th className="px-4 py-3">Traditional Pada sounds</th></tr></thead><tbody>{NAKSHATRA_REFERENCE.map(([name, , , , sounds]) => <tr key={name} className="border-t border-white/10"><td className="px-4 py-3 font-medium text-white">{name}</td><td className="px-4 py-3">{sounds}</td></tr>)}</tbody></table></div></section>
      <section><h2 className="text-3xl font-bold text-white">What Is a Nakshatra Lord?</h2><p>Each planet rules three Nakshatras: Ketu rules Ashwini, Magha and Mula; Venus rules Bharani, Purva Phalguni and Purva Ashadha; the Sun rules Krittika, Uttara Phalguni and Uttara Ashadha; the Moon rules Rohini, Hasta and Shravana; Mars rules Mrigashirsha, Chitra and Dhanishta; Rahu rules Ardra, Swati and Shatabhisha; Jupiter rules Punarvasu, Vishakha and Purva Bhadrapada; Saturn rules Pushya, Anuradha and Uttara Bhadrapada; Mercury rules Ashlesha, Jyeshtha and Revati.</p></section>
      <section><h2 className="text-3xl font-bold text-white">How Is Nakshatra Connected With Vimshottari Dasha?</h2><p>The birth Nakshatra determines the opening planetary lord in Vimshottari Dasha, but it does not automatically give the entire planetary period from birth. The remaining balance depends on the Moon's progress through the Nakshatra: <strong>remaining Nakshatra proportion × full Dasha period = approximate balance at birth.</strong> Calculate the exact timeline with the <Link to="/dasha-calculator/">Mahadasha and Antardasha tool</Link>.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Janma Nakshatra vs Lagna Nakshatra</h2><p>“My Nakshatra” normally means the Moon's Nakshatra. The Ascendant, Sun, Venus, Mars, Jupiter, Saturn, Rahu, Ketu and every other chart point also occupies a Nakshatra. Lagna Nakshatra refers specifically to the Ascendant degree and is interpreted separately in a deeper <Link to="/ai-kundli-analysis">Kundli analysis</Link>.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Which Nakshatra Is Best? Are Some Nakshatras Bad?</h2><p>There is no objectively best, luckiest or automatically harmful Nakshatra. Claims that Rohini is always best or that Mula, Ashlesha or Jyeshtha guarantees problems oversimplify astrology. Constructive and difficult expressions depend on Moon sign, house, pada, lord placement, aspects, conjunctions, Lagna, Dashas and divisional charts. Fear-based labels should be treated carefully.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Nakshatra and Marriage Compatibility</h2><p>Ashtakoota matching uses Moon signs and birth stars in factors such as Tara, Gana, Nadi, Yoni, Graha Maitri and Bhakoot. A responsible marriage analysis also considers the seventh house and lord, Venus, Jupiter, Navamsa, Manglik factors and relevant Dashas. Use <Link to="/free-kundali-matching">Kundli Matching</Link> rather than judging two people from Nakshatra names alone.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Can Two People Share a Nakshatra? Can It Change?</h2><p>Millions of people share each Nakshatra, and twins often share a Nakshatra and pada. Their Ascendants, houses, other planets and later life circumstances can still differ. Your birth Nakshatra remains fixed; today's transit Nakshatra changes as the Moon moves through roughly one Nakshatra per day.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Nakshatra Calculation Example</h2><p>Suppose the sidereal Moon longitude is 48° from Aries. Removing the first 30° gives 18° Taurus. Rohini spans 10°00′–23°20′ Taurus, so the Moon is in Rohini. It is 8° inside Rohini, which falls between 6°40′ and 10°00′: <strong>Rohini, Pada 3.</strong> The calculator automates this mapping after applying the correct timezone and sidereal reference.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Tropical vs Sidereal Zodiac</h2><p>Mainstream Western astrology commonly uses the tropical zodiac, while this calculator uses the Lahiri sidereal zodiac used in Vedic astrology. Different reference systems produce different longitudes. Before comparing tools, confirm the zodiac, ayanamsa, coordinates, timezone and daylight-saving handling. Read <Link to="/blog/vedic-vs-western-astrology">Vedic vs Western Astrology</Link> for the broader distinction.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Why Can Two Calculators Disagree?</h2><ol className="mt-4 list-decimal space-y-2 pl-6"><li>They use different ayanamsas.</li><li>The birth time contains an AM/PM or minute error.</li><li>The wrong city with a similar name was selected.</li><li>Historical timezone or daylight-saving rules differ.</li><li>The Moon lies extremely close to a Nakshatra boundary.</li></ol><p>When results disagree, compare the exact sidereal Moon longitude rather than only the final name.</p></section>
      <section><h2 className="text-3xl font-bold text-white">How Accurate Is an Online Nakshatra Calculator?</h2><p>With correct birth information and a reliable ephemeris, the astronomical placement can be calculated precisely. Calculation and interpretation are different: locating the Moon is astronomical computation; assigning traditional personality or predictive meaning belongs to Jyotisha. Astrological claims should not be confused with scientifically established causal effects. This page shows the exact longitude so the calculated result can be checked.</p></section>
      <section><h2 className="text-3xl font-bold text-white">What Should a Good Result Show?</h2><p>A useful result includes Janma Nakshatra, pada, Rashi, lord, exact Moon degree, deity and the naming sound for the relevant pada. The calculator above displays the astronomical result; the reference tables supply the traditional deity and sound. For deeper meaning, the lord must be read inside the complete birth chart.</p></section>
      <section><h2 className="text-3xl font-bold text-white">Continue With Related Astrology Tools and Guides</h2><p>Birth Nakshatra is one layer of the horoscope. These contextual resources help connect it to Rashi, Dashas, houses, compatibility, relationships, career, transits and responsible interpretation.</p><div className="not-prose mt-6 grid gap-3 sm:grid-cols-2">{contextLinks.map(([href, title, description]) => <Link key={href} to={href} className="card-glass block rounded-2xl border border-white/10 p-4 transition-colors hover:border-pink-500/40 hover:bg-pink-500/5"><h3 className="text-sm font-semibold text-pink-400">{title}</h3><p className="mt-2 text-xs leading-5 text-white/60">{description}</p></Link>)}</div></section>
      <section><h2 className="text-3xl font-bold text-white">Frequently Asked Questions About Nakshatra Calculator</h2><Accordion type="single" collapsible className="mt-4 border-t border-white/10">{NAKSHATRA_FAQS.map(([question, answer]) => <AccordionItem key={question} value={question} className="border-white/10"><AccordionTrigger className="text-left text-base text-white hover:no-underline">{question}</AccordionTrigger><AccordionContent className="text-base leading-7 text-white/70">{answer}</AccordionContent></AccordionItem>)}</Accordion></section>
      <section><h2 className="text-3xl font-bold text-white">Final Thoughts</h2><p>A proper Nakshatra Calculator does more than match a birthday to a static table. It calculates the Moon at the actual birth moment, divides the 360-degree zodiac into 27 lunar sectors and then into 108 padas. The result—Nakshatra, pada, Moon sign, lord, deity and naming sound—is one valuable layer of a much richer birth chart, not a person's entire identity.</p></section>
    </div>
  </article>;
}
